#pragma once
#include <Arduino.h>
#include "RTALStatus.h"

namespace RTALFxProtocol {
constexpr uint8_t SOF1=0x52, SOF2=0x46, VERSION=1;
enum Type:uint8_t { HELLO=0x01, HELLO_ACK=0x02, PING=0x03, PONG=0x04, SET_PARAM=0x10, GET_STATE=0x11, STATE=0x12, CLOCK_STATE=0x20 };
enum Param:uint8_t {
 P_DELAY_ENABLE=1,P_DELAY_FREEZE,P_DELAY_LEFT_MS,P_DELAY_RIGHT_MS,P_DELAY_FEEDBACK,P_DELAY_LEVEL,
 P_DELAY_LOWPASS_HZ,P_DELAY_HIGHPASS_HZ,P_DELAY_SATURATION,P_DELAY_CROSSFEED,P_DELAY_DUCK_AMOUNT,
 P_DELAY_DUCK_THRESHOLD_DB,P_DELAY_DUCK_RELEASE_MS,P_DELAY_MODE,P_DELAY_LEFT_DIV,P_DELAY_RIGHT_DIV,
 P_CLOCK_SOURCE=32,P_CLOCK_BPM_X100,P_LINK_STATUS=48,
 P_MOD_ENABLE=64,P_MOD_LFO_SHAPE,P_MOD_RATE_HZ,P_MOD_SYNC,P_MOD_DIVISION,P_MOD_DEPTH,
 P_MOD_STEREO_PHASE_DEG,P_MOD_SMOOTHING_MS,P_MOD_LFO_LEFT,P_MOD_LFO_RIGHT,P_MOD_EFFECT_SELECT,
 P_CHORUS_ENABLE=80,P_CHORUS_MIX,P_CHORUS_DELAY_MS,P_CHORUS_TONE_HZ,
 P_FLANGER_ENABLE=96,P_FLANGER_MIX,P_FLANGER_DELAY_MS,P_FLANGER_FEEDBACK,P_FLANGER_HPF_HZ,P_FLANGER_SATURATION,
 P_PHASER_ENABLE=112,P_PHASER_MIX,P_PHASER_STAGES,P_PHASER_FEEDBACK,P_PHASER_HPF_HZ,P_PHASER_SATURATION,P_PHASER_CENTER_HZ,
 P_WIDTH_ENABLE=120,P_WIDTH_AMOUNT,
 P_REVERB_ENABLE=122,P_REVERB_MIX,P_REVERB_SIZE,P_REVERB_DECAY,P_REVERB_DAMPING_HZ,P_REVERB_PREDELAY_MS
};
struct __attribute__((packed)) Frame { uint8_t sof1,sof2,version,type,seq,param; int32_t value; uint8_t crc; };
}

class RTALFxLink {
public:
 static RTALStatus begin();
 static void service();
 static void printReport();
private:
 static uint8_t crc8(const uint8_t*,size_t);
 static void parseByte(uint8_t);
 static void handleFrame(const RTALFxProtocol::Frame&);
 static void sendFrame(uint8_t,uint8_t,int32_t);
 static void sendState();
 static int32_t floatToQ16(float);
 static float q16ToFloat(int32_t);
};
